### ISSUE TITLE
js on drupal side - supposed to work?

### ISSUE THREAD

**Issue by Michael-wfw** [Shorthand/shorthand_connect_drupal#10]
should the Shorthand js files work on the drupal installation?
getting js errors in the console

![drupal-shorthand js errors](https://cloud.githubusercontent.com/assets/28265250/25585244/e8f22a3a-2e99-11e7-9847-e4eee856750a.PNG)

**Comment by dakala** [comment]
Currently, Drupal JS should work as all core assets are still being loaded but this is under review at the moment. See #7. Shorthand stories are (should be) complete and discrete entities being displayed in a Drupal site.

Let's know your use case, perhaps in the linked issue above?

**Comment by VladimirAus** [comment]
Outdated.
