### ISSUE TITLE
language drupal - ended up forcing 'und'

### ISSUE THREAD

**Issue by Michael-wfw** [Shorthand/shorthand_connect_drupal#11]
This is just a FYI - we have an old drupal7 install - and it was initially a single language site which we then tried to change to multilanguage before dropping the idea...
In any case $node-language always returns "de" in our setup - but e.g. the shorthand_story_id is at "und" - in **shorthand.module**

`/**
 * Create or update shorthand story node.
 *
 * @param object $node
 *   The newly-created or existing node.
 */
function update_node_data($node) {
  if (isset($node->shorthand_story_id)) {
    $node->original = isset($node->original) ? $node->original : NULL;
    debug($node,"full shorthand node:", "print_r");
    debug($node->shorthand_story_id,"node->shorthand_story_id:", "print_r");
    $shorthand_id = $node->shorthand_story_id[$node->language][0]['value'];
    $shorthand_id = $node->shorthand_story_id['und'][0]['value'];
    $node_id = $node->uid;
    $story = sh_copy_story($node_id, $shorthand_id);
    $head = _shorthand_fix_content_paths($story['url'], file_get_contents($story['path'] . '/component_head.html'));
    $node->shorthand_story_head[$node->language][0]['value'] = $head;
    $node->shorthand_story_head['und'][0]['value'] = $head;
    $body = _shorthand_fix_content_paths($story['url'], file_get_contents($story['path'] . '/component_article.html'));
    $node->shorthand_story_body[$node->language][0]['value'] = $body;
    $node->shorthand_story_body['und'][0]['value'] = $body;
    field_attach_update('node', $node);
  }
}
`

**Comment by dakala** [comment]
How Drupal handles multilingual fields depends on a number of factors. See https://www.drupal.org/docs/7/api/field-api/language-support-for-entity-fields. When no language has been assigned, Drupal defaults to using the constant `LANGUAGE_NONE` which is `und` - defined by ISO639-2 for "Undetermined". This meaning of the constant is simplistic as it also depends on whether you have enabled the Locale module or not. 

In `update_node_data($node)` function, Shorthand module simply refers to the language with which the node was saved - `$node->language`.

**Comment by VladimirAus** [comment]
Outdated
