### ISSUE TITLE
Improve UX when there's no SH account settings

### ISSUE THREAD

**Issue by dakala** [Shorthand/shorthand_connect_drupal#15]
Maybe add a message or/and denying access to node/add/shorthand-story

**Comment by dakala** [comment]
@simultech: Please see https://github.com/Shorthand/shorthand_connect_drupal/pull/17/commits/ff5a783a68cd4d88d54aba36f5efa52faf5bff71

**Comment by VladimirAus** [comment]
Seems fixed.
