### ISSUE TITLE
We need a component_footer.html 

### ISSUE THREAD

**Issue by dakala** [Shorthand/shorthand_connect_drupal#16]
**Problem:**

Currently a story is split into `component_article.html`, `component_head.html` and `component_html.html`.  Some Javascript code and `<script>` tags are in the body of the story in `component_article.html`. This causes issues with custom JS code that needs to be fired before Shorthand JS.

**Solution:**

1. It would be ideal if Shorthand can also return a `component_footer.html` that will contain all JS code.
2. In the meantime, we can also create a *shorthand_story_footer* field to hold JS code we extract from the `component_article.html` file.

**Comment by dakala** [comment]
@simultech: what do you think?

**Comment by simultech** [comment]
This should be solved in v2, closing for the moment (v2 js is a lot better structured/contained).
