### ISSUE TITLE
Rename module to Shorthand

### ISSUE THREAD

**Issue by dakala** [Shorthand/shorthand_connect_drupal#3]
I'd like to suggest renaming this module to just Shorthand. This will be in line with other available Drupal integrations such as:

* https://www.drupal.org/project/hubspot
* https://www.drupal.org/project/constant_contact
* https://www.drupal.org/project/campaignmonitor
* https://www.drupal.org/project/mailchimp

**Comment by dakala** [comment]
@simultech Hi. I've created a project for this on drupal.org (https://www.drupal.org/project/shorthand)  Are you happy for us to proceed with this shorter name please? Thanks

**Comment by simultech** [comment]
More than happy to rename the project to `shorthand`.  I assume we can leave the repo name the same (we already have a `shorthand/shorthand` private repo).

Project looks great - could you add team@shorthand.com (shorthand) account to the project as well?

**Comment by dakala** [comment]
Cool. I've added `shorthand` to d.o. project with full admin rights. I suppose at some point we'll have to decide when to push to the drupal.org repo from here as a lot of Drupal projects now do.  It'd be nice too if you can create a Shorthand organisation on drupal.org so we can add them as sponsor. You'll get a page like this: https://www.drupal.org/british-council

Sure, the repo here can remain as is, only the Drupal module name's going to change in my next PR.

**Comment by simultech** [comment]
@dakala so sorry for the delay!  Wanted to test it out, and swamped by our upcoming release.  I've now played around and looks great!  Merged.

**Comment by simultech** [comment]
Is there anything else that needs to be done here in terms of hooking up to the Drupal project?

**Comment by dakala** [comment]
Hey @simultech, great to hear from you. I've been wondering what's up. Thanks for the merge. I've already created a project on drupal.org - https://www.drupal.org/project/shorthand It'll be great to have you join drupal.org too and once I get your details, I'll add you to project as maintainer. 

Next step will be to push the repo to drupal.org once we've agreed on how we want to manage it. Previously, all projects were managed on drupal.org but in the last year or so, a lot of projects are moving to github and syncing back to drupal.org. See https://www.drupal.org/project/og. That's the type of model we may want to consider.

In the meantime, I'll also be looking into a Drupal 8 version of the integration. 

By the way, did you say you were looking into a single integration API for PHP?

**Comment by simultech** [comment]
Yes assigning this to me, I will definitely look into this ASAP (sorry again, smashed with the new version).  In terms of the single integration API, in WP I've created a dropdown in settings, for v1 and v2 as there are slight differences, and probably a staged rollout.  I think I'll write a branch for this in Drupal and get you to look over it?

https://github.com/Shorthand/shorthand_connect_wordpress/tree/master/src/includes

**Comment by dakala** [comment]
Ok, I'll take a look later.

**Comment by VladimirAus** [comment]
Outdated issue. Don't think there is a reason to rename git hub repo @ckortekaas ?
If not please close the task.
