### ISSUE TITLE
Multi-user mode

### ISSUE THREAD

**Issue by dakala** [Shorthand/shorthand_connect_drupal#4]
I'm interested in a multi-user mode potentially for a team of editors. 

## Problem:

Since Shorthand accounts and access details are for individual users, there's no way for a team member to access stories created by another user.

## Solution:

Allow a Drupal site to have multiple Shorthand accounts and control access by the Drupal permission system.

**Comment by simultech** [comment]
There is a Shorthand major release coming soon that will address this, and will provide collaboration support to both Shorthand and API users (including team level and organisation level tokens).  This should address the issue of collaborators, but will require additional functionality in the Drupal plugin (I've already written the Wordpress plugin support but we are still iterating through to make sure that we haven't missed anything on the API side).
