### ISSUE TITLE
Review management of assets

### ISSUE THREAD

**Issue by dakala** [Shorthand/shorthand_connect_drupal#7]
Shorthand provides all CSS, JS and images required. Do we envisage ever needing Drupal assets on Shorthand story pages?

**Comment by simultech** [comment]
I would imagine there is some potential if a user wants to use a specific theme (header/footer/widget) that might need assets?

**Comment by dakala** [comment]
Yes, even in our use case we often need the header/footer regions but Drupal pulls in tons of CSS and JS files out of which only a small part is responsible for those regions. Perhaps I should have put the issue description in another way.

Still thinking about it. Maybe we can come up with something now that I'm putting more effort into this work during our 2-week sprint that's just started.

**Comment by VladimirAus** [comment]
Outdated.
